BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`user_type_id`	INTEGER NOT NULL,
	FOREIGN KEY(`user_type_id`) REFERENCES `user_types`(`id`)
);
CREATE TABLE IF NOT EXISTS `user_types` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `products` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`price`	NUMERIC NOT NULL,
	`amount`	INTEGER NOT NULL,
	`is_available`	INTEGER NOT NULL,
	`category_id`	INTEGER NOT NULL DEFAULT 1,
	FOREIGN KEY(`category_id`) REFERENCES `categories`(`id`)
);
CREATE TABLE IF NOT EXISTS `orders` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_id`	INTEGER NOT NULL,
	`order_at`	TEXT NOT NULL,
	`status`	TEXT NOT NULL,
	`pay_at`	TEXT,
	FOREIGN KEY(`user_id`) REFERENCES `users`(`id`)
);
CREATE TABLE IF NOT EXISTS `order_products` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`order_id`	INTEGER NOT NULL,
	`product_id`	INTEGER NOT NULL,
	`amount`	INTEGER NOT NULL,
	FOREIGN KEY(`product_id`) REFERENCES `products`(`id`),
	FOREIGN KEY(`order_id`) REFERENCES `orders`(`id`)
);
CREATE TABLE IF NOT EXISTS `categories` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`is_available`	INTEGER
);
INSERT INTO `categories` VALUES (1,'owoce',1);
INSERT INTO `categories` VALUES (2,'warzywa',1);
INSERT INTO `products` VALUES (1,'ziemniak',2.25,15,1,1);
INSERT INTO `products` VALUES (2,'banan',1.75,10,1,2);
INSERT INTO `products` VALUES (3,'cebula',150,2,0,1);
COMMIT;
